nombre = input("ingrese su nombre")
print(nombre)
print(type(nombre))
edad = int(input("ingrese su edad"))
print(edad)
print(type(edad))
estado = bool(input("estado de matricula: activo/inactivo" ))
print(estado)
print(type(estado))
peso = int(input("ingrese su peso"))
print(peso)
print(type(peso))
